name: getto_sync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_vector_icons: ^2.0.0
  http: ^1.2.1
  http_parser: ^4.0.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.0.11
  cached_network_image: ^3.2.3
  mobile_scanner: ^3.5.1
  permission_handler: ^11.0.1
  another_flushbar: ^1.12.32

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/getto.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/getto.png"
  min_sdk_android: 21
  ios_content_mode: scaleAspectFit

flutter:
  uses-material-design: true
  assets:
    - assets/icons/getto.png
